### ISSUE TITLE
Problem with <class 'AttributeError'>: 'NoneType' object has no attribute 'Objects' during the installation 

### ISSUE THREAD

**Issue by Krounet** [LubomirJagos/FreeCAD-OpenEMS-Export#26]
Hello,

I'm testing OpenEMS and i would like to test FreeCAD-OpenEMS-Export. During the installation I got this message in the FreeCad console :

`12:42:20  APP_CONTEXT set to FreeCAD
12:42:20  No Blender interface available.
12:42:20  No Blender interface available.
12:42:20  No Blender interface available.
12:42:20  No Blender interface available.
12:42:20  No Blender interface available.
12:42:20  No Blender interface available.
12:42:20  No Blender interface available.
12:42:20  No Blender interface available.
12:42:20  Traceback (most recent call last):
  File "C:/Users/mathi/AppData/Roaming/FreeCAD/Macro/FreeCAD-OpenEMS-Export.FCMacro", line 27, in <module>
    dlgPanel = FOE_mod.ExportOpenEMSDialog()
  File "C:\Users\mathi\AppData\Roaming\FreeCAD\Macro\FreeCAD-OpenEMS-Export/ExportOpenEMSDialog.py", line 181, in __init__
    self.initLeftColumnTopLevelItems()
  File "C:\Users\mathi\AppData\Roaming\FreeCAD\Macro\FreeCAD-OpenEMS-Export/ExportOpenEMSDialog.py", line 1165, in initLeftColumnTopLevelItems
    items = self.cadHelpers.getOpenEMSObjects(filterStr)
  File "C:\Users\mathi\AppData\Roaming\FreeCAD\Macro\FreeCAD-OpenEMS-Export\utilsOpenEMS\GuiHelpers\CadInterface.py", line 66, in getOpenEMSObjects
    currentObjects = self.getObjects()
  File "C:\Users\mathi\AppData\Roaming\FreeCAD\Macro\FreeCAD-OpenEMS-Export\utilsOpenEMS\GuiHelpers\FreeCADHelpers.py", line 86, in getObjects
    return FreeCAD.ActiveDocument.Objects
<class 'AttributeError'>: 'NoneType' object has no attribute 'Objects'`

I put the files in the FreeCad macro repertory like this :

![image](https://github.com/LubomirJagos/FreeCAD-OpenEMS-Export/assets/23114989/66859bd4-119a-415d-8489-5d2023c2df0d)

My FreeCad version is 0.20.2.

Someone had already this issue before ?

**Comment by ChristianHonisch** [comment]
Ran into the same issue when I tried to see if the macro is working.

For me this error only appears if there is no file open in FreeCAD.
Afer creating a blank project (File->New) it works for me.
